// Package a2ui implements the server side of the A2UI v0.9 tag protocol:
// the system prompt section that teaches the LLM to optionally emit ONE
// <a2ui-json> block after its markdown answer, tag extraction from complete
// and streamed LLM output, structural validation of the message list, and a
// one-shot corrective retry for invalid blocks.
//
// Full protocol validation happens client-side with the @a2ui/web_core zod
// schemas; the Go checks are structural only — enough to reject malformed
// blocks early and to drive the corrective retry.
package a2ui

import (
	"encoding/json"
	"fmt"
)

const (
	// OpenTag and CloseTag delimit the A2UI block in LLM output.
	OpenTag  = "<a2ui-json>"
	CloseTag = "</a2ui-json>"

	// CatalogID mirrors the client-side catalog id (src/catalog/index.ts in
	// swifty-agent-fe); duplicated on purpose since the catalog is client-only.
	CatalogID = "https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json"

	// UIActionPrefix marks chat messages the client synthesizes from surface
	// actions; the prompt teaches the LLM how to handle them.
	UIActionPrefix = "[UI_ACTION]"
)

type m = map[string]any

// The few-shot examples are generated by builders so UI structure changes
// only need a builder edit — the prompt stays in sync automatically.

func buildAlertListExample() []any {
	const surfaceID = "alerts-overview-1"
	return []any{
		m{"version": "v0.9", "createSurface": m{"surfaceId": surfaceID, "catalogId": CatalogID}},
		m{"version": "v0.9", "updateComponents": m{
			"surfaceId": surfaceID,
			"components": []any{
				m{"id": "root", "component": "Column", "children": []any{"alerts-title", "alerts-list"}},
				m{"id": "alerts-title", "component": "Text", "variant": "h3", "text": m{"path": "/title"}},
				m{"id": "alerts-list", "component": "List", "direction": "vertical", "children": m{"componentId": "alert-card", "path": "/alerts"}},
				m{"id": "alert-card", "component": "Card", "child": "alert-body"},
				m{"id": "alert-body", "component": "Column", "children": []any{"alert-head", "alert-desc", "alert-since", "alert-ack"}},
				m{"id": "alert-head", "component": "Row", "justify": "spaceBetween", "align": "center", "children": []any{"alert-name", "alert-severity"}},
				m{"id": "alert-name", "component": "Text", "variant": "h4", "text": m{"path": "name"}},
				m{"id": "alert-severity", "component": "Badge", "variant": "destructive", "text": m{"path": "severity"}},
				m{"id": "alert-desc", "component": "Text", "text": m{"path": "description"}},
				m{"id": "alert-since", "component": "Text", "variant": "caption", "text": m{"path": "startsAt"}},
				m{"id": "alert-ack", "component": "Button", "variant": "primary", "child": "alert-ack-label", "action": m{"event": m{"name": "ack_alert", "context": m{"alertname": m{"path": "name"}, "severity": m{"path": "severity"}}}}},
				m{"id": "alert-ack-label", "component": "Text", "text": "Acknowledge"},
			},
		}},
		m{"version": "v0.9", "updateDataModel": m{
			"surfaceId": surfaceID,
			"path":      "/",
			"value": m{
				"title": "2 firing alerts",
				"alerts": []any{
					m{"name": "HighErrorRate", "severity": "critical", "description": "Error rate above 5% on service checkout for 10m.", "startsAt": "2026-08-17 09:12:00"},
					m{"name": "MySQLReplicationLag", "severity": "warning", "description": "Replica lag is 45s on db-order-replica-2.", "startsAt": "2026-08-17 08:40:00"},
				},
			},
		}},
	}
}

func buildMetricsReportExample() []any {
	const surfaceID = "qps-report-1"
	return []any{
		m{"version": "v0.9", "createSurface": m{"surfaceId": surfaceID, "catalogId": CatalogID}},
		m{"version": "v0.9", "updateComponents": m{
			"surfaceId": surfaceID,
			"components": []any{
				m{"id": "root", "component": "Column", "children": []any{"report-title", "qps-chart", "qps-table"}},
				m{"id": "report-title", "component": "Text", "variant": "h3", "text": m{"path": "/title"}},
				m{"id": "qps-chart", "component": "Chart", "variant": "line", "data": m{"path": "/rows"}, "xKey": "time", "series": []any{
					m{"key": "qps", "label": "QPS"},
					m{"key": "errors", "label": "Errors"},
				}, "height": 240},
				m{"id": "qps-table", "component": "Table", "caption": "Hourly QPS of service checkout", "columns": []any{
					m{"key": "time", "header": "Time"},
					m{"key": "qps", "header": "QPS"},
					m{"key": "errors", "header": "Errors"},
				}, "rows": m{"path": "/rows"}},
			},
		}},
		m{"version": "v0.9", "updateDataModel": m{
			"surfaceId": surfaceID,
			"path":      "/",
			"value": m{
				"title": "Service checkout QPS (last 3 hours)",
				"rows": []any{
					m{"time": "10:00", "qps": 1240, "errors": 3},
					m{"time": "11:00", "qps": 1685, "errors": 12},
					m{"time": "12:00", "qps": 2210, "errors": 5},
				},
			},
		}},
	}
}

func buildSilenceFormExample() []any {
	const surfaceID = "silence-form-1"
	return []any{
		m{"version": "v0.9", "createSurface": m{"surfaceId": surfaceID, "catalogId": CatalogID}},
		m{"version": "v0.9", "updateComponents": m{
			"surfaceId": surfaceID,
			"components": []any{
				m{"id": "root", "component": "Card", "child": "form-body"},
				m{"id": "form-body", "component": "Column", "children": []any{"form-title", "alertname-field", "hours-field", "comment-field", "submit-btn"}},
				m{"id": "form-title", "component": "Text", "variant": "h4", "text": "Create alert silence"},
				m{"id": "alertname-field", "component": "TextField", "label": "Alert name", "value": m{"path": "/alertname"}},
				m{"id": "hours-field", "component": "TextField", "label": "Duration (hours)", "variant": "number", "value": m{"path": "/hours"}},
				m{"id": "comment-field", "component": "TextField", "label": "Comment", "value": m{"path": "/comment"}},
				m{"id": "submit-btn", "component": "Button", "variant": "primary", "child": "submit-label", "action": m{"event": m{"name": "create_silence", "context": m{
					"alertname": m{"path": "/alertname"},
					"hours":     m{"path": "/hours"},
					"comment":   m{"path": "/comment"},
				}}}},
				m{"id": "submit-label", "component": "Text", "text": "Create silence"},
			},
		}},
		m{"version": "v0.9", "updateDataModel": m{
			"surfaceId": surfaceID,
			"path":      "/",
			"value":     m{"alertname": "HighErrorRate", "hours": "2", "comment": ""},
		}},
	}
}

func renderExample(name string, messages []any) string {
	encoded, err := json.Marshal(messages)
	if err != nil {
		panic(fmt.Sprintf("a2ui: failed to marshal %s example: %v", name, err))
	}
	return fmt.Sprintf("---BEGIN %s---\n%s\n%s\n%s\n---END %s---", name, OpenTag, encoded, CloseTag, name)
}

// PromptSection is the system prompt section injected into the chat template.
// It is passed as a template VARIABLE value (never inlined into the FString
// template) because its JSON braces would otherwise be parsed as placeholders.
var PromptSection = fmt.Sprintf(`## Interactive UI (A2UI v0.9)

Besides markdown you can render interactive UI surfaces with the A2UI v0.9 protocol.

- WHEN: only when the answer presents structured data — alert lists, tabular/SQL query results, metric series or trends, or a form the user should fill and confirm. For explanations, how-tos and casual conversation, answer in plain markdown WITHOUT any A2UI block.
- HOW: write a brief markdown summary first (1-3 sentences), then append exactly ONE UI block wrapped between %s and %s. The block content is a JSON array of A2UI messages, with no prose inside the tags.
- Message order: createSurface first, then updateComponents (the "root" component first), then updateDataModel.
- Every message is {"version":"v0.9", ...} and contains exactly one of createSurface / updateComponents / updateDataModel.
- createSurface needs a surfaceId that is unique per reply (kebab-case, e.g. "alerts-overview-3") and catalogId "%s".
- Components use the flat wire format {"id":"...","component":"Card",...props}; children are referenced by component id. Every surface must define a component with id "root".
- Data binding: {"path":"/x"} reads the surface data model (absolute path). Inside a List item template use relative paths like {"path":"name"}. List template binding: "children":{"componentId":"<template-id>","path":"/items"}.
- Buttons fire actions: "action":{"event":{"name":"<action_name>","context":{...}}} where context values are literals or {"path"} bindings (bindings also work inside list templates and carry current form values).
- Copy real data (tool results, documents) verbatim into updateDataModel — NEVER invent values. If there is no real data, do not render a surface.
- Text and data values render as PLAIN TEXT: never put markdown syntax (**bold**, _italics_, backticked code, [links]) inside component text, table cells or data model values.
- Available components:
  - Basic: Text {text, variant?: h1|h2|h3|h4|h5|caption}, Image {url}, Row {children, justify?: start|center|end|spaceBetween, align?: start|center|end}, Column {children}, List {direction?: vertical|horizontal, children}, Card {child}, Divider {}, Button {child, variant?: primary|borderless, action}, TextField {label, value, variant?: number|longText}, CheckBox {label, value}, Slider {label?, value, min?, max?}, DateTimeInput {label?, value, enableDate?, enableTime?}, Tabs, Modal, Icon, Video, AudioPlayer, ChoicePicker.
  - Extensions: Table {caption?, columns:[{key,header}], rows: array or {"path"} binding}, Chart {variant: bar|line|area|pie, data: array or {"path"} binding, xKey, series:[{key,label?}], height?}, Badge {text, variant?: default|secondary|destructive|outline}, Alert {title, description?, variant?: default|destructive}, Progress {value: 0-100, label?, showValue?}, Item {title, description?, variant?: default|outline|muted}.
- Any component may set "weight": <number> for flex sizing inside Row/Column.
- Follow-up actions: a user message starting with "%s" reports that the user triggered an action in a previously rendered surface; it carries the action name and a JSON context including current form values. Handle it like a normal request (run tools if needed), then confirm with markdown and, when useful, a new surface with a fresh surfaceId.

### A2UI examples

%s
%s
%s`,
	OpenTag, CloseTag, CatalogID, UIActionPrefix,
	renderExample("ALERT_LIST_EXAMPLE", buildAlertListExample()),
	renderExample("METRICS_REPORT_EXAMPLE", buildMetricsReportExample()),
	renderExample("FORM_EXAMPLE", buildSilenceFormExample()),
)
