// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pb/swifty.proto

package __

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwiftyCache_Get_FullMethodName    = "/pb.SwiftyCache/Get"
	SwiftyCache_Set_FullMethodName    = "/pb.SwiftyCache/Set"
	SwiftyCache_Delete_FullMethodName = "/pb.SwiftyCache/Delete"
)

// SwiftyCacheClient is the client API for SwiftyCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwiftyCacheClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error)
}

type swiftyCacheV2Client struct {
	cc grpc.ClientConnInterface
}

func NewSwiftyCacheClient(cc grpc.ClientConnInterface) SwiftyCacheClient {
	return &swiftyCacheV2Client{cc}
}

func (c *swiftyCacheV2Client) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, SwiftyCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftyCacheV2Client) Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, SwiftyCache_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftyCacheV2Client) Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForDelete)
	err := c.cc.Invoke(ctx, SwiftyCache_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwiftyCacheServer is the server API for SwiftyCache service.
// All implementations must embed UnimplementedSwiftyCacheServer
// for forward compatibility.
type SwiftyCacheServer interface {
	Get(context.Context, *Request) (*ResponseForGet, error)
	Set(context.Context, *Request) (*ResponseForGet, error)
	Delete(context.Context, *Request) (*ResponseForDelete, error)
	mustEmbedUnimplementedSwiftyCacheServer()
}

// UnimplementedSwiftyCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwiftyCacheServer struct{}

func (UnimplementedSwiftyCacheServer) Get(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSwiftyCacheServer) Set(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedSwiftyCacheServer) Delete(context.Context, *Request) (*ResponseForDelete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSwiftyCacheServer) mustEmbedUnimplementedSwiftyCacheServer() {}
func (UnimplementedSwiftyCacheServer) testEmbeddedByValue()                     {}

// UnsafeSwiftyCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwiftyCacheServer will
// result in compilation errors.
type UnsafeSwiftyCacheServer interface {
	mustEmbedUnimplementedSwiftyCacheServer()
}

func RegisterSwiftyCacheServer(s grpc.ServiceRegistrar, srv SwiftyCacheServer) {
	// If the following call pancis, it indicates UnimplementedSwiftyCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwiftyCache_ServiceDesc, srv)
}

func _SwiftyCache_Get_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftyCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftyCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(SwiftyCacheServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftyCache_Set_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftyCacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftyCache_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(SwiftyCacheServer).Set(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftyCache_Delete_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftyCacheServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftyCache_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(SwiftyCacheServer).Delete(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SwiftyCache_ServiceDesc is the grpc.ServiceDesc for SwiftyCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwiftyCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SwiftyCache",
	HandlerType: (*SwiftyCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SwiftyCache_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _SwiftyCache_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SwiftyCache_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/swifty.proto",
}
