# ip address
bind 0.0.0.0
# port
port 6379

# whether AOF is enabled
appendonly yes
# AOF file name
appendfilename appendonly.aof
# AOF fsync policy. always | everysec | no
appendfsync everysec
# number of AOF commands before a rewrite
auto-aof-rewrite-after-cmds 1000
