package filter

import (
	"errors"
	"hash/fnv"
	"math/bits"
)

// BloomFilter is a space efficient probabilistic data structure used to test
// whether a key belongs to a set. It may report false positives but never
// false negatives.
type BloomFilter struct {
	m          int      // length of the bitmap in bits
	hashedKeys []uint64 // hash values of all keys added to the filter
}

// NewBloomFilter creates a bloom filter whose bitmap is m bits long.
func NewBloomFilter(m int) (*BloomFilter, error) {
	if m <= 0 {
		return nil, errors.New("m must be positive")
	}
	return &BloomFilter{
		m: m,
	}, nil
}

// hashKey returns the first base hash h1 of a key, derived with FNV-1a 64.
func hashKey(key []byte) uint64 {
	h := fnv.New64a()
	_, _ = h.Write(key)
	return h.Sum64()
}

// hashDelta returns the second base hash h2 of a key. h2 is obtained by
// rotating h1 right by 17 bits, which keeps h1 and h2 linearly independent.
func hashDelta(h1 uint64) uint64 {
	return bits.RotateLeft64(h1, -17)
}

// Add adds a key to the bloom filter.
func (bf *BloomFilter) Add(key []byte) {
	bf.hashedKeys = append(bf.hashedKeys, hashKey(key))
}

// Exist reports whether the key may exist in the bitmap generated by Hash.
// Note that false positives are possible.
func (bf *BloomFilter) Exist(bitmap, key []byte) bool {
	// Without a bitmap the key cannot be judged, so it is assumed to exist.
	// Reporting false here would turn into a false negative and hide existing
	// keys.
	if bitmap == nil {
		return true
	}
	if len(bitmap) < 2 {
		return false
	}
	// Number of hash functions k.
	k := bitmap[len(bitmap)-1]
	// Bits available for key bits. The trailing byte storing k is excluded,
	// otherwise hash bits would corrupt the stored k.
	bitLen := uint64(len(bitmap)-1) << 3

	// The first base hash function is h1 = FNV-1a 64.
	// The second base hash function is h2 = rotateRight(h1, 17).
	// Every hash function used below is generated as a linear combination of
	// h1 and h2: the i-th hash function is gi = h1 + i * h2.

	// h1
	h1 := hashKey(key)
	// h2
	delta := hashDelta(h1)
	for i := uint64(0); i < uint64(k); i++ {
		// gi = h1 + i * h2
		targetBit := (h1 + i*delta) % bitLen
		// Check the mapped bit: if it is 0 the key definitely does not exist.
		if bitmap[targetBit>>3]&(1<<(targetBit&7)) == 0 {
			return false
		}
	}

	// All bits mapped by the key are set, so the key is assumed to exist
	// (with a false positive probability).
	return true
}

// Hash generates the bitmap of the filter. The last byte stores the value of k.
func (bf *BloomFilter) Hash() []byte {
	// k: the optimal number of hash functions derived from m and n.
	k := bf.bestK()
	// Empty bitmap whose last byte stores k.
	bitmap := bf.bitmap(k)
	bitLen := uint64(len(bitmap)-1) << 3

	// The first base hash function is h1 = FNV-1a 64.
	// The second base hash function is h2 = rotateRight(h1, 17).
	// Every hash function used below is generated as a linear combination of
	// h1 and h2: the i-th hash function is gi = h1 + i * h2.
	for _, hashedKey := range bf.hashedKeys {
		// hashedKey is h1 and delta is h2.
		delta := hashDelta(hashedKey)
		for i := uint64(0); i < uint64(k); i++ {
			// The i-th hash function gi = h1 + i * h2.
			// The bit to mark as 1.
			targetBit := (hashedKey + i*delta) % bitLen
			bitmap[targetBit>>3] |= 1 << (targetBit & 7)
		}
	}

	return bitmap
}

// Reset resets the filter.
func (bf *BloomFilter) Reset() {
	bf.hashedKeys = bf.hashedKeys[:0]
}

// KeyLen returns the number of keys held by the filter.
func (bf *BloomFilter) KeyLen() int {
	return len(bf.hashedKeys)
}

// bitmap returns an empty bitmap. The trailing byte stores k.
func (bf *BloomFilter) bitmap(k uint8) []byte {
	// bytes = bits / 8, rounded up.
	bitmapLen := (bf.m + 7) >> 3
	bitmap := make([]byte, bitmapLen+1)
	// The last byte stores k.
	bitmap[bitmapLen] = k
	return bitmap
}

// bestK derives the optimal number of hash functions from m and n, where m is
// the bitmap length in bits and n is the number of keys: k = ln2 * m / n.
func (bf *BloomFilter) bestK() uint8 {
	if len(bf.hashedKeys) == 0 {
		return 1
	}
	// k is clamped to [1, 30].
	k := min(max(69*bf.m/100/len(bf.hashedKeys), 1), 30)
	return uint8(k)
}
